### ISSUE TITLE
ISO check doesn't work properly

### ISSUE THREAD

**Issue by phunni** [wiemag/arch-headless#3]
I attempted running this with on the latest (at the time of writing) arch iso (2019.11.01) and I got the following error:

> archlinux-2019.11.01-x86_64.iso is not an ISO-type file.  

I've checked the MD5sums and the iso is valid.

**Comment by wiemag** [comment]
Yes. Command 'file -b archlinux-official.iso' no longer reports it to be ISO8660.
I fixed it by removing this command.
I wrote this script a long ago to install arch linux on 10-year-old and older computers. So the 32-bit architecture was default. Today 32 is no longer supported by Arch Linux.
I should have made some more fixes when I fixed this issue, but I have no time to make the proper adjustments. I have added the xz compression as another option.

I have run the  script on the November 2019 ISO and it created a new ISO for a headless machine.
I started the ISO under a qemu virtual machine and was able to ssh into the machine without a password (as expected). I have not tried burning the ISO into a CD/DVD or placing it on a USB flash disk.

I do not think that I will be maintaining this script any longer for two reasons. First is that the archiso package is a perfect tool. Second is that people who (like you) look for such solutions are clever/knowledgeable enough to modify this script themselves if necessary. 
I will not remove it from github, because it may give people some ideas what they can do in their own scripts.

Hope the ISO works in real world not only under qemu virtual machine.
